### ISSUE TITLE
0x52 - Differences in spot price vs AMM prices can be abused to completely misrepresent the holdings of a UniV3 LP tokens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-arcadia-judging#144]
0x52

medium

# Differences in spot price vs AMM prices can be abused to completely misrepresent the holdings of a UniV3 LP tokens

## Summary

`UniswapV3#getPrincipleAmounts` uses the current valuation base on oracles to determine the amount of tokens in a UniV3 LP position. This can be abused by creating an LP position that is outside this price that causes the composition of the token to be entirely different than it actually is. Due to the tiny differences in ticks, this can occur with minute differences between oracle and pool price.

## Vulnerability Detail

[UniswapV3AM.sol#L268-L283](https://github.com/sherlock-audit/2023-12-arcadia/blob/main/accounts-v2/src/asset-modules/UniswapV3/UniswapV3AM.sol#L268-L283)

    function _getPrincipalAmounts(
        int24 tickLower,
        int24 tickUpper,
        uint128 liquidity,
        uint256 priceToken0,
        uint256 priceToken1
    ) internal pure returns (uint256 amount0, uint256 amount1) {
        // Calculate the square root of the relative rate sqrt(token1/token0) from the trusted USD price of both tokens.
        // sqrtPriceX96 is a binary fixed point number with 96 digits precision.
        uint160 sqrtPriceX96 = _getSqrtPriceX96(priceToken0, priceToken1);

        @audit-issue bases liquidity on oracle prices rather than pool prices
        (amount0, amount1) = LiquidityAmounts.getAmountsForLiquidity(
            sqrtPriceX96, TickMath.getSqrtRatioAtTick(tickLower), TickMath.getSqrtRatioAtTick(tickUpper), liquidity
        );
    }

When calculating the tokens held by an LP position, the `sqrtPriceX96` is used to determine the holdings of the LP token. If this price is outside of the ticks of the LP position it will show the composition of the LP token as either completely `token0` (below) or completely `token1` (above). We can now abuse this to completely misrepresent the holdings of the token.

Assume the following prices for ETH:

Oracle - $1000.01
Pool - $1000

Due to the precision of ticks, pool is a single tick higher than the oracle. Now imagine a position of ETH-USDC that is a single tick position. At the oracle tick, the contract thinks this position would be entirely USDC but at the actual tick of the pool it is entirely ETH. This allows a user to completely bypass exposure limits. As stated in my other submission, these limits are very important for a debt market. 

## Impact

Single tick positions can be used to completely bypass exposure limits

## Code Snippet

[UniswapV3AM.sol#L268-L283](https://github.com/sherlock-audit/2023-12-arcadia/blob/main/accounts-v2/src/asset-modules/UniswapV3/UniswapV3AM.sol#L268-L283)

## Tool used

Manual Review

## Recommendation

This mainly affects LP with extremely narrow spread. There are two potential approaches to fix this. First could be to restrict the spread of the LP token. For example LP shouldn't be allowed if their spread is less than 1000 ticks. The other approach would be to check assets with both the pool price and the oracle price and compare the results. If the assets differ by more than 1% then the transaction should revert.

**Comment by zzykxx** [comment]
Escalate

Derived assets like UniswapV3 positions also have a max exposure parameter expressed in USD that helps limit this impact. Furthermore, an attacker cannot technically control the market direction, meaning the way the protocol interprets what assets the position is constituted by cannot be controlled for longer periods, although it's possible to keep withdrawing and depositing the position with new tick parameters, but this has a gas cost.

Because the UnsiwapV3 positions have an extra maximum exposure controlled in USD the mechanic is not fully broken. The issue can't be abused to cause a monetary loss either, which leads me to think this should not be considered a medium severity issue.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Derived assets like UniswapV3 positions also have a max exposure parameter expressed in USD that helps limit this impact. Furthermore, an attacker cannot technically control the market direction, meaning the way the protocol interprets what assets the position is constituted by cannot be controlled for longer periods, although it's possible to keep withdrawing and depositing the position with new tick parameters, but this has a gas cost.
> 
> Because the UnsiwapV3 positions have an extra maximum exposure controlled in USD the mechanic is not fully broken. The issue can't be abused to cause a monetary loss either, which leads me to think this should not be considered a medium severity issue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by IAm0x52** [comment]
> Furthermore, an attacker cannot technically control the market direction, meaning the way the protocol interprets what assets the position is constituted by cannot be controlled for longer periods, although it's possible to keep withdrawing and depositing the position with new tick parameters, but this has a gas cost.

Wanted to make a comment on the feasibility of this. Both prices are public prices so there is no need to withdraw and deposit repeatedly. You can write a very simple smart contract that checks the price of each then creates the proper position and deposits it in a single transaction. 

I also acknowledge that it can't be used to directly steal funds. As stated in my submission, the concern is bypassing exposure limits and creating bad debt (loss to LPs) through improper risk control.

**Comment by zzykxx** [comment]
> Wanted to make a comment on the feasibility of this. Both prices are public prices so there is no need to withdraw and deposit repeatedly. You can write a very simple smart contract that checks the price of each then creates the proper position and deposits it in a single transaction.

This is correct, as soon as the position is deposited with the correct timing and tick parameters it is misrepresented in the protocol in terms of the assets it represents, which can bypass the exposure limits in terms of an asset. What I was trying to say is that the relative price between the two assets can change while the position is deposited, which will also change the assets it represents from the point of view of the protocol and an attacker has no control over this, unless he withdraws and re-deposit the position with updated tick parameters.

**Comment by Banditx0x** [comment]
Just wanted to chime in that a Uniswap liquidity position can at minimum be one `tickSpacing` wide, never 1 tick wide, so a "single tick position" does not actually exist. The minimum tick spacing for a 0.05% pool is 10, and minimum tick spacing for 0.3% pool is 60.

**Comment by nevillehuang** [comment]
@Banditx0x @zzykxx Thanks for the insightful comments, this is new to me. Could you point me to possible resources that indicates your above comment?

> Just wanted to chime in that a Uniswap liquidity position can at minimum be one tickSpacing wide, never 1 tick wide, so a "single tick position" does not actually exist. The minimum tick spacing for a 0.05% pool is 10, and minimum tick spacing for 0.3% pool is 60.

**Comment by Banditx0x** [comment]
@nevillehuang From page 3 of the Uniswap v3 whitepaper: https://uniswap.org/whitepaper-v3.pdf :

_"UNI governance also has the ability to add additional fee tiers. When it adds a new fee tier, it can also define the tickSpacing (see Section 6.1) corresponding to that fee tier. Once a fee tier is added to the factory, it cannot be removed (and the tickSpacing cannot be changed). The initial fee tiers and tick spacings supported are 0.05% (with a tick spacing of 10, approximately 0.10% between initializable ticks), 0.30% (with a tick spacing of 60, approximately 0.60% between initializable ticks), and 1% (with a tick spacing of 200, approximately 2.02% between ticks.)"_

For some more context, this works by restricting `tickLower` and `tickUpper` of a liquidity position to be multiples of the `tickSpacing`. For example if tickSpacing is 10, and tickLower is 0, the narrowest possible liquidity position would have a tickUpper of 10.

From page 5 of the whitepaper:

_"Not every tick can be initialized. The pool is instantiated with a
parameter, tickSpacing (𝑡𝑠 ); only ticks with indexes that are divisi- ble by tickSpacing can be initialized. For example, if tickSpacing is 2, then only even ticks (...-4, -2, 0, 2, 4...) can be initialized. Small choices for tickSpacing allow tighter and more precise ranges, but may cause swaps to be more gas-intensive (since each initialized tick that a swap crosses imposes a gas cost on the swapper)"_

Also described here: https://docs.uniswap.org/contracts/v3/reference/core/interfaces/pool/IUniswapV3PoolImmutables

**Comment by Czar102** [comment]
From my understanding, the impact of this issue is not uncapped, as it can be configured by `UniswapV3AM` exposure setting, nevertheless, in some cases exposure to concrete assets may bypass global controls.

Let me abstract from the current protocol to show my approach in judgment here.
Let's say we are considering a protocol X which has exposure constraints per asset. It accepts two different versions of WETH. The exposure constraint is separate for both, and even though one can be set to 1000, the second to 1000, the total (nearly) equivalent exposure to ETH is 2000, which exceeds all exposure settings.
Nevertheless, I don't consider this an issue. The admin setting the constraints must be aware of the correlation of some assets in exposure settings.

In this case however, this correlation is not so straightforward, but it should be clear that as any asset's price in a pair LP position goes towards zero, the LP position's value goes towards zero. So, one can say that the pair LP position gives exposure to both tokens, even though only one may be held by it.
It should be fine to take only a fraction of a total exposure into account as long as this exposure is accurately limited by other constraints, which is the case here. (think: other WETH exposure limit, even though highly correlated, it can have a separate limit)

Hence, I think this issue should be an informational one, please correct me if I'm misunderstanding any part of it.

**Comment by Czar102** [comment]
Result:
Low
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [zzykxx](https://github.com/sherlock-audit/2023-12-arcadia-judging/issues/144/#issuecomment-1970912748): accepted
